### ISSUE TITLE
Ajout de node dans le project graph

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#10]
Lors de l'ajout d'un node pour le project graph, la fenetre de creation du node ne se ferme pas après avoir appuyer sur OK alors qu'en arriere plan on voit le node nouvellement crée. 
Si on rappuie sur OK, on recrée un nouveau node, sans que la fenetre se ferme. 
Il faut appuyer sur Cancel pour retourner au project graph.

**Comment by bfiorito** [comment]
Fixed, will be included in the next releases.
