### ISSUE TITLE
Amélioration de l'ergonomie de la configuration des convertisseurs

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#13]
En tant qu'administrateur, je veux que la colonne "Attached column'" soit grisé pour les champs possédant un type "CONVERTER_PARAMETER_INTERN" afin que l'administrateur puisse comprendre rapidement la colonne à afficher. 

Pour les autres types, il faut griser la colonne "Value" et non pas "Attached Column".

Il faudrait trouver un moyen ergonomique de faire la distinction entre colonnes à éditer et colonnes non éditables (peut être une couleur)

Idem pour datasets[fields], request filters, dataset services, application plugin, application service

**Comment by mgond** [comment]
Fixed, will be included in the next releases.
