### ISSUE TITLE
Amélioration de la définition d'une source de données MongoDB

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#14]
En tant qu'administrateur, afin d'améliorer l'ergonomie de l'interface, je souhaite remplir les champs suivants pour définir une source de données JDBC :
- host 
- port
- nom de la base
au lieu de définir l'URL

Toujours afin d'améliorer l'ergonomie de ce composant, je souhaite un composant plié par défaut intitulé "configuration avancée" contenant l'URI attachment

**Comment by mgond** [comment]
Already included
