### ISSUE TITLE
Suppression d'un rôle

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#16]
En tant qu'administrateur 
Je peux supprimer un rôle uniquement s'il n'est pas utilisé dans aucune authorisation d'application, authorisation de datastorage, projet module. 

S'il est utilisé, la suppression est interdite et un rapport de l'utilisation du rôle est affiché pour aider l'administrateur à supprimer le rôle.

**Comment by bfiorito** [comment]
Will be fixed in the next releases.
