### ISSUE TITLE
Reconnexion source de données MySQL

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#17]
MySQL entraine une déconnexion automatique au bout d'un certain temps d'utilisation. 
Il faudrait modifier la datasource MySQL pour qu'elle se reconnecte automatiquement. 
Voir : http://stackoverflow.com/questions/17901034/how-to-set-autoreconnect-property-for-mysql-db-url-in-play-framework-configurati

**Comment by bfiorito** [comment]
Fixed, will be included in the next releases.
