### ISSUE TITLE
Catégorisation des colonnes

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#21]
En tant qu'utilisateur je visualise mes enregistrements. Je désire visualiser plus de colonnes. 

Je sélectionne une catégories de colonnes. Ainsi je peux sélectionner le groupe « Astrométrie » qui m'affichera les colonnes Ra, Dec, Référentiel 

Cette sélection ce fait à partir d'un nouveau menu "catégories" qui s'affiche uniquement si des colonnes appartiennent à une catégorie. Ce nouveau menu ressemble à celui des colonnes.

**Comment by mgond** [comment]
Will be included in the next releases.
