### ISSUE TITLE
GroupBy et Having

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#22]
En tant qu'administrateur je veux pouvoir définir un GROUP BY + HAVING dans mon dataset à la place de la clause WHERE (uniquement en mode libre et pas en wizard). 
Actuellement, uniquement le WHERE est autorisé. 

On veux également pouvoir configurer si l'on fait une requête distinct ou non.

**Comment by mgond** [comment]
Included in version 3.0beta2
