### ISSUE TITLE
Sort by alias dataset

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#23]
J'ai un nouveau souci, qui n'est pas trop sournois à priori: j'ai un 
dataset avec des colonnes qui ont le même nom dans leur définition SQL, 
mais pas le même alias (genre i.name AS instrument_name, et ft.name 
frame_type_name) . Malheureusement lorsque je trie sur la colonne 
instrument, ou frame type il rajoute au statement SQL "ORDER BY name 
DESC", tout de suite sanctionné par un 
"com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: 
Column 'name' in order clause is ambiguous" côté serveur. Et du coup un 
plantage côté client. 

Il suffirait de faire un order par l'alias (ici instrument_name) si il 
est disponible pour que la même requête fonctionne.

**Comment by mgond** [comment]
Fixed, will be included in the next releases.
