### ISSUE TITLE
Intégration de Mizar avec un graphe

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#24]
Le but étant de cliquer sur un jeu de données d'un graphe et représenter entièrement le jeu de données :  
 - La représentation sera faite à partir d'un MOC pour l'astro (req)
 - La représentation sera faite à l'aide d'un WMTS pour la planéto ou par l'ensemble des enregistrements (option)

**Comment by mgond** [comment]
Included in version 3.0beta2
