### ISSUE TITLE
La mise en forme des forms de type desktop n'est pas respectée en 2.4.1

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#3]
Le form (de type desktop) n'est pas positionné au milieu de l'écran alors qu'il l'était en 2.1. 
En conséquence les composants du form ne respectent pas la disposition définie dans l'interface d'administration. 
Le layout du composant contenant le desktop est de type "form" ce qui ne permet pas de récuperer les bornes de l'écran (contrairement au layout "absolu"). 
Nous avons contourné en remettant les .js de la 2.1 dans client-user/js/components/forms

**Comment by bfiorito** [comment]
Fixed, will be included in the next releases.
