### ISSUE TITLE
Problem with  MODE_SERVER_OUTBOUND mode in ProxyApp.java

### ISSUE THREAD

**Issue by MarcNicolas** [SITools2/SITools2-core#36]
In ProxyApp.java in fr.cnes.applications.basic package, there is a problem with mode server outbound (mode 6 in administration configuration).
The server not appending the appending the remaining part of the current request URI  which hasn't been routed yet.

line 162 : 
redirector = new Redirector(getContext(), param1.getValue(),Integer.parseInt(param3.getValue()));

Whereas it should be something like
 if (Integer.parseInt(param3.getValue()) == 6 )
redirector = new Redirector(getContext(),param1.getValue().concat("{rr}") ,Integer.parseInt(param3.getValue()));

**Comment by mgond** [comment]
Fixed, will be included in the next releases
