### ISSUE TITLE
Problème pour intègrer des fichiers au format tar.gz dans les archives

### ISSUE THREAD

**Issue by DATAQTIS-NG** [SITools2/SITools2-core#42]
L’intégration dans l’archive au format  zip/tar.gz/tar des fichiers eux-même tar.gz, ne semble pas possible aujourd’hui.

**Comment by mgond** [comment]
Je n'arrive pas à reproduire le problème, pour pouvoir le reproduire pouvez vous me décrire le scénario que vous mettez en place et le nom des fichiers que vous essayer d'inclure dans l'archive.

De mon côté j'ai essayé de faire un dataset avec un champs qui pointe vers un fichier tar.gz : '/sitools/datastorage/user/storage/order/' || prop_id || '/PREVIEW.A001.tar.gz' et j'utilise la ressource StreamingOrderResource pour générer un zip ou un tar.gz contenant ces fichiers PREVIEW.A001.tar.gz

Merci d'avance pour vos précisions
