### ISSUE TITLE
Problème lors de l'ouverture de plusieurs pages externes pour la V3

### ISSUE THREAD

**Issue by MarcNicolas** [SITools2/SITools2-core#43]
Si dans la définition d'un dataset nous avons une colonne défini avec une featureType en URL et en beaviExternal URL (view in Desktop), coté client quand on ouvre un des liens cela marche bien, mais si on veut on ouvrir un deuxième cela ne marche pas cela nous ramène vers le premier onglet ouvert au lieu d'en ouvrir un second.

**Comment by bfiorito** [comment]
Fixed, will be included in the next releases.
