### ISSUE TITLE
pb avec dataset services coté admin

### ISSUE THREAD

**Issue by MarcNicolas** [SITools2/SITools2-core#50]
Bonjour,

Je suis en version 3.0 stable, et j'ai un soucis j'ai une soixante de datasets, et je peux pas accéder à tous dans la dropdownlist de dataset services. Il ne m'en propose que 20- 25. Et même en cherchant par le nom de mon dataset.
J'ai regardé avec firebug, et effectivement il y a une requete de ce style qui passe : 
http://.../sitools/datasets?_dc=1448459663216&page=1&start=0&limit=25

Il y a une limite, forcément il ne peut pas récupérer tous les datasets !! C'est très très embetant comme bug, car du coup je ne peux mettre aucun service à plus de la moitié de mes datasets.

Merci de faire le nécessaire et d'indiquer comment faire pour patcher cela.

**Comment by mgond** [comment]
Will be fixed in the next release
