### ISSUE TITLE
Bug dans le multi-dataset query form

### ISSUE THREAD

**Issue by DATAQTIS-NG** [SITools2/SITools2-core#51]
A la création d'un formulaire multi-datasets, les concepts partagés ne sont pas visibles bien que les jeux de données partagent la même collection ainsi que le même mapping de dictionnaire.

Conséquences:
- pas de concepts paratagés visibles dans FormInformaiton > Shared Concepts
- impossible de mapper le champ localisation du composant graphique mappanel.

**Comment by mgond** [comment]
Quelle est la version sur laquelle vous avez le problème ?

**Comment by DATAQTIS-NG** [comment]
En 3.0

**Comment by mgond** [comment]
Nous venons de faire le test sur cette version (à partir d'une installation vierge de SITools2) et nous n'arrivons pas à reproduire le problème.
Nous avons réalisés :
* Création de 2 datasets
* Création d'un template de dictionnaire
* Création d'un dictionnaire avec 2 concepts
* attachement de chaque concept à une colonne pour le dataset1
* attachement d'un seul concept à une colonne pour le dataset2
* Création d'une collection avec les 2 datasets
* Création d'un formulaire multidataset à partir de cette collection. Seul le concept1 est affiché.

Pourriez vous essayer de reproduire ces étapes pour voir si le problème viens de la version de SITools2 ou de votre configuration ou pouvez vous nous donner quelques informations sur votre configuration pour pouvoir reproduire le problème.

Merci d'avance
