### ISSUE TITLE
Configuration bugs of SITOOLS2 and eclipse

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#53]
Hello,
I have met some configuration problems of eclipse and sitools,
     In the project “org.restlet.ext.solr”, there is a JAVA problem with core container and its function load. (core.execute(handler, request, response))

    The problem comes when I try to run the project (fr.cnes.sitools.core). 
    I have added the jar(solr-core-4.5.0.jar) needed in the JAVA build path. 
   
   Thank you very much for your help.

**Comment by mgond** [comment]
Hello Guanjiwang,

Have you declared a target platform with the correct libraries ? 
The list of libraries is described in the documentation that you can download here : [http://sourceforge.net/projects/sitools2/files/Documentation/V3.0/DG-SITOOLS2-V3-1.0.pdf/download](http://sourceforge.net/projects/sitools2/files/Documentation/V3.0/DG-SITOOLS2-V3-1.0.pdf/download)

Be careful not to add the Solr or Lucene libraries in the target platform.

Do not hesitate to ask again if you have any other questions or problems.

Mathieu

**Comment by guanjiwang2016** [comment]
Hi Mathieu,
    Thank you for your reply.
    Yes, I did the configuration according to the pdf before.


And i only tick the three jar;
But it doesn't work for the projects.

Can I discuss a little about the configuration next Monday?

Thank you.
Have a good weekend.

Best regards,
Guanji

**Comment by guanjiwang2016** [comment]
Hi Mathieu,
    And here is my version of Eclipse and JRE attached. Is it the 
correct version to execute and compile the sitools? As i can start the 
sitools and webpage by terminal in linux but can't with eclipse.




java version "1.6.0_37"
OpenJDK Runtime Environment (IcedTea6 1.13.9) (6b37-1.13.9-1ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)



Thank you.
Have a good day.
