### ISSUE TITLE
Les paramètres énumérés ne sont pas montrés dans l'interface admin

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#57]
Dans cette application :
https://github.com/SITools2/Astronomy-Extension-Server/blob/master/fr.cnes.sitools.ext.astronomy/src/fr/cnes/sitools/extensions/astro/application/OpenSearchVOApplicationPlugin.java

Le paramètre protocol est défini ainsi :
   param = new ApplicationPluginParameter();
    param.setName("protocol");
    param.setDescription("Set the service protocol");
    param.setValueType("xs:enum[" + Protocol.DETECT_AUTOMATICALLY.name() + "," + Protocol.CONE_SEARCH_PROTOCOL.name() + "," + Protocol.SIMPLE_IMAGE_ACCESS_PROTOCOL.name() + "]");
    param.setValue(Protocol.DETECT_AUTOMATICALLY.name());
    this.addParameter(param);

L'interface administration devrait proposer le choix entre trois champs, ce qui n'est pas le cas actuellement

**Comment by bfiorito** [comment]
Fixed. Will be included in the next release.
