### ISSUE TITLE
Modification de l'url des liens du Footers

### ISSUE THREAD

**Issue by DATAQTIS-NG** [SITools2/SITools2-core#58]
Dans chacun de mes projets j'ai modifié l'url pour label.legalInformations, label.contacts et label.help. Mais à chaque fois que je clique sur un lien j'ai le message suivant : 

_todo open window with link /sitools/client-portal/resources/html/fr/legalinformations.html with name : label.legalInformations__

**Comment by bfiorito** [comment]
Fixed. Will be included in the next release.
