### ISSUE TITLE
Creation Dataset avec Criteria

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#6]
J'ai trouvé un petit bug lors de l'ajout d'un criteria pour un dataset. 
Cela se situe au niveau de l'Operateur. Si on l'ajoute grâce à la dropdownlist cela marche mais vu que cette cellule est editable, si comme moi on le fait "à la main", en mettant par exemple =, cela ne convertit pas l'opérateur en EQ et donc cela fait une server error lors de la creation du dataset (Je mets toute l'erreur apparu dans la console d'Eclipse en fin de mail). 
Il faudrait soit ne pas rendre editable cette cellule soit avoir un listener en plus.

**Comment by bfiorito** [comment]
Fixed, will be included in the next releases.
