### ISSUE TITLE
Problem of 'DataSetLink' in web client-admin

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#60]

**Comment by guanjiwang2016** [comment]
Hello,
   I find a bug in sitools2.
   In web page client-admin, choose a dataset, in 'Field setup' -> 'Feature Type' ->DataSetLink ,
    I choose Behavior as Icon and when I want to choose a dataset to be linked,
   In the list, **only first 25 datasets are shown** , the bugs is the same for every dataset,  help me investigate the problem a little, please.

Thank you.
Guanji

**Comment by bfiorito** [comment]
Fixed. Will be in the next release.
