### ISSUE TITLE
info légale

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#67]
Erreur remontée en cliquant sur info légale, (ou contact, ou aide) sur un projet.
Cela fonctionne avec les liens sur le portail.
![form2](https://cloud.githubusercontent.com/assets/8714542/16452359/504af88e-3e08-11e6-86dd-c56b97c97118.png)

**Comment by mgond** [comment]
Duplicate from #58 fixed in version 3.0.2
