### ISSUE TITLE
vue bloquée lors de l'upload d'une image

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#7]
Après l'upload d'une image depuis le feature type, au lieu de me redonner la main pour sélectionner cette image. Tout la fenêtre est figée, comme si une popup modal c'était ouverte (sauf que ce n'est pas le cas). Du coup je n'ai pas la main pour sélectionner l'image que je viens d'uploader pour l'intégrer à mon feature type de download. 
J'ai du faire un refresh de la page pour reprendre la main. Cependant l'image c'était bien uploadée.

**Comment by bfiorito** [comment]
Fixed, will be included in the next releases.
