### ISSUE TITLE
Improvement of the module 'FormAsMenu'

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#70]
Hello,
    1.  Following the issue #69, I add a loading mask to the module 'FormAsMenu', can we add & release the feature to the next version of sitools, please?
    2. And is there any solution for us to cache the 'Forms' for faster the operation next time?

Thank you.
Regards,
guanji

**Comment by malapert** [comment]
Hi, it should be done on the 3.0.3. Can I close it ?

**Comment by guanjiwang2016** [comment]
Hi,
   Yes, please.
   Thank you.
regards,
guanji
