### ISSUE TITLE
[QUESTION] Module window position 

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#79]
Hello,
      The scenario: 
       1. First http://idoc-solar-portal-test.ias.u-psud.fr.
       2. Maximize the module body by clicking the button on the upper-right of window.
       3. Search forms -> select "STEREO"

Then the result:
![image](https://cloud.githubusercontent.com/assets/16957363/20664493/655636ae-b553-11e6-8d9c-a7369f60f9ec.png)

      Attention please, the scenario appears only in Chrome and only for STEREO form but not in Firefox or for other forms.
      And the extra line is called "ux-taskbar"  in source element.

Thank you,
regards,
Guanji

**Comment by MedocIAS** [comment]
Hi,

Reproduced in Chrome version 53.02785 
Not reproduced in Chrome version 55.0.2883.87

I guess you can close that one 
Best regards, 
Pablo
