### ISSUE TITLE
bug dans le module projectGraph

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#8]
J'ai trouvé une petite "coquille" dans le code javascript du ProjectGraphModule.js. 
Dans le jsonStore à la ligne 74 on trouve : 
} 
label : i18n.get("label.records"), 
columnName : 'description', 
selected : true 
} 
Alors que la colonne records est déjà défini et que la colonne description est défini juste après. Cela donne la preview que je joins avec 2 colonnes Records.

**Comment by bfiorito** [comment]
Fixed, will be included in the next releases.
