### ISSUE TITLE
[BUG] Query Form - DATE_BETWEEN component

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#82]
Hello,
    A bug for DATE_BEWTEEN component in client_admin as captured picture,
    `Default From : {$TODAY}  - 20 ` can't be validated while  `Default From : {$TODAY}  - 6 `  is Ok.
![selection_232](https://cloud.githubusercontent.com/assets/16957363/25739688/3cb8dd30-3183-11e7-98ac-292150e1a665.jpg)
![selection_231](https://cloud.githubusercontent.com/assets/16957363/25739690/3f2ef2c0-3183-11e7-9650-24d04b8389fb.jpg)

Thank you.
Regards,
Guanji

**Comment by bfiorito** [comment]
Fixed in commit d90250d4c30fc00c8c901e4ab4c4628dee8e403d
