### ISSUE TITLE
[QUESTION] PLOT FUNCTION IN NEW IHM TEMPLATE

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#83]
Hello,
   In the project configuration, if 
   1. Navigation Mode = 'Desktop'
   2. Template =  'full-desktop-without-header-footer.project.ftl'

The plot function in the result window doesn't work.
![image](https://cloud.githubusercontent.com/assets/16957363/26247595/e999d6f0-3c9e-11e7-8ac5-e7ceff07bb46.png)

I removed the invocation of loading footerLogo in js and the plot function works now. Do you have other solution to adapt the new template?

Regards,
Guanji

**Comment by bfiorito** [comment]
Fixed in commit 7bd0c1ab04474312e9b4f8f493647fe32bc4c538
