### ISSUE TITLE
Mauvaise URL sitools2 dans mail envoyé

### ISSUE THREAD

**Issue by DATAQTIS-NG** [SITools2/SITools2-core#84]
Dans les mails automatique le lien donné pour sitools n'est pas bon.

We are pleased to inform you that your user account has been modified on SITools2. You can can access data as defined in the SITools2 url. (http://dataqtis-ng.cst.cnes.fr:8182/sitools/client-user/)

**Comment by hubertnouhen** [comment]
Fixed on dev-3 and will be available in the next release.
