### ISSUE TITLE
[ISSUE]PROJECT GRAPH UPDATE

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#86]
Hello,
    I test the ProjectAdministration (Project resources by Restlet),
![selection_299](https://user-images.githubusercontent.com/16957363/27090025-5ae71572-505c-11e7-9e43-24a9ede49b17.jpg)

    For
```
http://localhost:8184/sitools/projects/{projectId}/start
http://localhost:8184/sitools/projects/{projectId}/stop 
```
  They work very well but there is a problem when I want to update the graph(PUT doesn't work but GET works):
![selection_297](https://user-images.githubusercontent.com/16957363/27090070-7719fb56-505c-11e7-9a09-bde0acbf0056.jpg)

I get the response of failure, here is the screenshot:
![selection_298](https://user-images.githubusercontent.com/16957363/27090009-4f883c1a-505c-11e7-9f17-28384eefebc3.jpg)

Can you help me update the latest information to the graph of project, please?
Thank you for your help.
Regards,
Guanji

**Comment by bfiorito** [comment]
Hi Guanji,

We test the project graph resource and it works for us.

Two possibilities :

- Maybe you don't have the right authorizations to access the resource. In that case : Go to SITools administration page -> Application -> ProjectAdministration and add an authorization for you user.

- Or maybe as you use CURL, you don't have set the good **Content-Type** in the HTTP header request to **application/json** and you get a server error. This is very important to parse your json into a Graph object (in java code)
