### ISSUE TITLE
QUESTION[MULTI DATASETS QUERY FORM]

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#88]
Hello,
    I try to create a multi datasets query form for different datasets but it doesn't work.
    Can I get some tutorial/documentation about it, please?

   Thanks,
   regards,
    guanji

**Comment by malapert** [comment]
Hello Guanji,

Basically, You need :
1/ create a dictionary
2/ for each dataset that you wish, you need to map the entries of your
dictionary with the attributes of the datasets
3/ Then create a multi datasets form and set the datasets and the
dictionary. Then you will see only the common attributes of your dictionary
that you map with each dataset.
4/ Then, this is the same thing than the classic form.

Regards,
Jean-Christophe

**Comment by guanjiwang2016** [comment]
Hello Jean-Christophe,
        Thank you for your reply but I tried the same process, the multi-dataset can't take any attributes into its query form. You can see my operation as follows:
  

1. Create a collection where I add two datasets inside.
![selection_407](https://user-images.githubusercontent.com/16957363/29816046-04da84d2-8cb3-11e7-9557-42714b7642b8.jpg)


2. Create a dictionary structure where I define three concept properties whose values equal the names of the attributes in the datasets.
![selection_408](https://user-images.githubusercontent.com/16957363/29816051-08679cde-8cb3-11e7-9ac8-11e656d7e170.jpg)
![selection_409](https://user-images.githubusercontent.com/16957363/29816058-0bf44604-8cb3-11e7-81e1-cc09a0f7f44c.jpg)
3. Create a dictionary using the structure defined above, then I add information in the 'Dictionary information' and 'Select concepts'
       
![image](https://user-images.githubusercontent.com/16957363/29820306-62dca2ca-8cc4-11e7-9a1b-09771ecf6eb6.png)
![image](https://user-images.githubusercontent.com/16957363/29820309-64dcca14-8cc4-11e7-8acb-2e8ab80a4795.png)

![image](https://user-images.githubusercontent.com/16957363/29820312-68104b66-8cc4-11e7-8a20-6000800dde53.png)


4.   Create a multi datasets query form using the collection and dictionary but I can't build and see the shared concept in the form information, then in properties page, no properties detected.  
![image](https://user-images.githubusercontent.com/16957363/29820315-6b8a177c-8cc4-11e7-9caf-ebf068c5e7b2.png)
![image](https://user-images.githubusercontent.com/16957363/29820334-6eedf76c-8cc4-11e7-9eca-b57e27448467.png)
![image](https://user-images.githubusercontent.com/16957363/29820343-729b6c0a-8cc4-11e7-9f86-83e0f813f484.png)


5. In the result window, no filters are shown.
![image](https://user-images.githubusercontent.com/16957363/29820371-8c9ef66c-8cc4-11e7-9c1e-376ae45501cd.png)


Can you please explaine how to correctly map the filter and the attributes of each datasets?
Thank you for your help.
Regards,
Guanji

**Comment by malapert** [comment]
Hi,

Have you manage to create your multi-dataset ? I think you miss the step to
map each entry of your dictionnary with the attributes of each dataset part
of your collection. This feature is available on the screen that displays
all datasets.

Regards,
Jean-Christophe

Le 29 août 2017 2:18 PM, "guanjiwang2016" <notifications@github.com> a
écrit :
