### ISSUE TITLE
[bug]Renaming A Column does not impact user interface & preferences files

### ISSUE THREAD

**Issue by ImLAJILI** [SITools2/SITools2-core#89]
I encountered a problem trying to rename a dataset column from the admin interface in fieldsetup (get_segment). The change affects the xml data file under the map/ folder, but the change has no impact on the user interface. I thought it was a problem related to the saved preferences. I removed the preferences for this dataset (in / data / storage / public and admin) and refreshed but vainly. Knowing that if I directly edit the datasetOverview file (the dataset preference file) the label changes its value and that in the  JSON response that returns the server I find the new column name.

![screenshot](https://user-images.githubusercontent.com/33125447/32060232-74bc1c28-ba6e-11e7-8d49-eca20cc1f928.png)

![screenshot2](https://user-images.githubusercontent.com/33125447/32061684-9a2b4502-ba72-11e7-9090-35c4f01c04e9.png)

Regards,
Imène

**Comment by J-Christophe** [comment]
It was not a bug but an old saved preference.

**Comment by malapert** [comment]
It was not a bug but an old saved preference.
