### ISSUE TITLE
Feature Type Image et Thumbnail

### ISSUE THREAD

**Issue by malapert** [SITools2/SITools2-core#9]
J'ai un soucis quand je crée sur une colonne un feature type Image avec comme thumbnail une image qui vient d'une autre colonne. 
Dans la livegrid, le thumbnail qui apparait provient de l'image elle meme, comme si j'avais choisi le 'use automatic thumbnail from image'. 
J'ai vérifié dans le xml du dataset, la colonne du thumbnail est bien la bonne et j'ai aussi vérifié que sitools2 avait accés au thumbnail. 
Sur le png attaché, la premiere colonne (avec l'image en noir et blanc) est la colonne que j'ai configuré avec le thumbnail sur une autre colonne. Et la deuxieme colonne (avec l'image en couleur) est celle sur laquelle la premiere est censée pointé pour faire sa preview.
![1408](https://cloud.githubusercontent.com/assets/8714542/8196429/3de67854-148c-11e5-9d49-30d466a8acb4.png)

**Comment by bfiorito** [comment]
Fixed, will be included in the next releases.
