### ISSUE TITLE
[ISSUE] Download zip - file not found error is not tranlsated from key

### ISSUE THREAD

**Issue by mmebsout** [SITools2/SITools2-core#91]
Sitools Version : 3.0-beta1 (PSUP instance)
Using Firefox 57.0 (64 bits)

In a dataset that has the fr.cnes.sitools.resources.order.DirectOrderResource plugin configured.
When clicking on the download button after selecting several rows to download : 
if files are not found the popup error only displays the label's key for internationalization.

![filenotfound](https://user-images.githubusercontent.com/7287245/33322740-7fccb6ae-d44a-11e7-9fdc-60268a62fdc7.png)

**Comment by hubertnouhen** [comment]
Fixed in v3.1.2
