### ISSUE TITLE
[Typo]  a green check is shown when datasource test fails

### ISSUE THREAD

**Issue by mmebsout** [SITools2/SITools2-core#93]
Sitools Version : 3.0-beta1 (PSUP instance)
Using Firefox 57.0 (64 bits)

![capture du 2017-12-05 11-50-17](https://user-images.githubusercontent.com/7287245/33603694-b8bce61e-d9b3-11e7-827d-140b2c35d5aa.png)

**Comment by hubertnouhen** [comment]
Fixed in v3.1.2
