### ISSUE TITLE
[Typo] label.description.Mini isn't short

### ISSUE THREAD

**Issue by mmebsout** [SITools2/SITools2-core#94]
Sitools Version : 3.0-beta1 (PSUP instance (but I've fix it there))
Using Firefox 57.0 (64 bits)

Using the project-graph module the column titles for description and definitions are not 'def' or 'desc' when they are refering to the internationalization key 'label.***Mini' 

It would work better to have in both files 
```
client-public-3.0/res/i18n/en/gui.properties
client-public-3.0/res/i18n/fr/gui.properties
```
the following values
```
l 1351 label.descriptionMini = Desc
l 1352 label.definitionMini = Def
```

![labelmini](https://user-images.githubusercontent.com/7287245/33619800-65931a02-d9e6-11e7-80dc-5f1aeabe359b.png)

**Comment by hubertnouhen** [comment]
Labels has been shrunk in v3.1.2
